### ISSUE TITLE
Race condition in tests

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/iotanalytics-gearpump-rule-engine#24]
During startup, the deployer script can fail if it connects before the system user is created.
@wagmarcel Do you think we should prevent frontend from hosting before the system users are created?
As a quickfix, it is better to implement a check during authorization.

Here is the error message:
```
wait-for-it.sh: localhost:8090 is available after 12 seconds
[ActorSystemImpl] Illegal request, responding with status '400 Bad Request': Illegal HTTP message start
Starting deployment script
Traceback (most recent call last):
  File "src/app.py", line 55, in <module>
    oisp_client.auth(conf["username"], conf["password"])
  File "/usr/local/lib/python2.7/dist-packages/oisp/client.py", line 244, in auth
    expect=200)
  File "/usr/local/lib/python2.7/dist-packages/oisp/client.py", line 431, in post
    authorize_as, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oisp/client.py", line 402, in _make_request
    raise OICException(expect, resp)
oisp.client.OICException: Exception during API call
HTTP code: 401, 200 was expected
Error message: {
    "message": "Not Authorized",
```

**Comment by wagmarcel** [comment]
@arkocal yes. I think a loop to try again if it fails after, say, 5 seconds, would be fine.

**Comment by arkocal** [comment]
#25 fixed this. Closing.
